name: Code Checks
on:
  push:
  pull_request:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compile
        run: mvn -B compile --file pom.xml
      - name: Test
        run: mvn -B test --file pom.xml
